### ISSUE TITLE
Contao Austria Day

### ISSUE THREAD

**Issue by fiedsch** [may17/awesome-contao#4]
Beim Contao Austria Day findet man auf der verlinkten Seite Infos aus dem Jahr 2014. Das war wohl der aktuellste Austria Day und passt so gesehen. Allerdings finde ich, daß 5 Jahre alte Infos die "awesomeness" etwas schmälern und den Eindruck hinterlassen könnten, das "da nichts mehr passiert" -- was ja nicht stimmt, denn https://www.contao-austria.at ist sehr aktiv. 

Meinungen dazu?

Bei der <gelegenheit: https://www.contao-austria.at könnte noch mit in die "Community Organizations & Groups" aufgenommen werden.

**Comment by may17** [comment]
Gebe dir Recht. Auch die Nordtage Website ist offline und für den nrw das gilt ähnliches.

**Comment by may17** [comment]
Ich habe nun den Austria day entfernt und dafür die Contao Austria Gruppe hinzugefügt. Vielleicht wären generelle Regeln gut, wie z.B das nur Events in der Liste stehen die gewisse Kriterien erfüllen wie z.b. fand mindestens zweimal statt in den letzten 3 Jahren oder so.
